import { SITE_COLORS } from "@/utility/strings";

export const CONSULT_PHYSICIAN_HERO_CONSTANTS = {
  BORDER_RADIUS: "16px",
  MIN_HEIGHT: "280px",
  PADDING: "24px",
  CONTENT_GAP: "16px",
  BADGE_GAP: "8px",
  TITLE_FONT_SIZE: "28px",
  TITLE_FONT_WEIGHT: "800",
  TITLE_LINE_HEIGHT: "1.2",
  DESCRIPTION_FONT_SIZE: "16px",
  DESCRIPTION_FONT_WEIGHT: "400",
  DESCRIPTION_LINE_HEIGHT: "1.5",
  BADGE_FONT_SIZE: "14px",
  BADGE_FONT_WEIGHT: "600",
  BADGE_PADDING: "6px 12px",
  BADGE_BORDER_RADIUS: "9999px",
  BADGE_DOT_SIZE: "8px",
  OVERLAY_GRADIENT: `linear-gradient(98deg, ${SITE_COLORS.NAVY_DARK} 0%, ${SITE_COLORS.BLUE_DEEP} 55%, rgba(0, 71, 141, 0.85) 100%)`,
  BADGE_BACKGROUND: "rgba(255, 255, 255, 0.95)",
  BADGE_DOT_COLOR: SITE_COLORS.LIGHT_GREEN_5,
  BADGE_TEXT_COLOR: SITE_COLORS.TEXT_PRIMARY,
} as const;
