import { TRANSLATION_KEYS } from "@/utility/strings";

export const COUNTDOWN_TIMER_DEFAULTS = {
  WRAPPER_PADDING: "20px",
  WRAPPER_BORDER_RADIUS: "24px",
  CARD_PADDING: "20px 32px",
  CARD_BORDER_RADIUS: "16px",
  CARD_MIN_WIDTH: "240px",
  STACK_GAP: "8px",
  TICK_INTERVAL_MS: 1000,
  SECONDS_PER_MINUTE: 60,
  TIME_PAD_LENGTH: 2,
  TIME_PAD_CHAR: "0",
} as const;

export const COUNTDOWN_TIMER_TYPOGRAPHY = {
  LABEL: {
    FONT_SIZE: "16px",
    FONT_WEIGHT: "600",
    LINE_HEIGHT: "100%",
    LETTER_SPACING: "0",
  },
  VALUE: {
    FONT_SIZE: "64px",
    FONT_WEIGHT: "800",
    LINE_HEIGHT: "100%",
    LETTER_SPACING: "0",
  },
} as const;

export const COUNTDOWN_TIMER_FALLBACKS = {
  LABEL: "STARTS IN",
  SHOWCASE_TITLE: "Countdown timer",
  SHOWCASE_COMPLETED: "Timer reached zero.",
} as const;

export const COUNTDOWN_TIMER_CONSTANTS = {
  LABEL: TRANSLATION_KEYS.COUNTDOWN_TIMER.LABEL,
  SHOWCASE: {
    TITLE: TRANSLATION_KEYS.COUNTDOWN_TIMER.SHOWCASE.TITLE,
    COMPLETED: TRANSLATION_KEYS.COUNTDOWN_TIMER.SHOWCASE.COMPLETED,
  },
  DEMO: {
    DURATION_SECONDS: 292,
  },
} as const;
