import { SITE_COLORS } from "@/utility/strings";

export const OPTION_SELECT_MODES = {
  SINGLE: "single",
  MULTIPLE: "multiple",
} as const;

export const OPTION_SELECT_GROUP_DEFAULTS = {
  MAX_WIDTH: "629px",
  GAP: "12px",
  OPTIONS_GAP: "12px",
  BORDER_RADIUS: "12px",
  OPTION_PADDING: "12px 20px",
  OPTION_MIN_HEIGHT: "44px",
} as const;

export const OPTION_SELECT_GROUP_TYPOGRAPHY = {
  QUESTION: {
    FONT_SIZE: "18px",
    FONT_WEIGHT: 700,
    LINE_HEIGHT: "1.3",
  },
  OPTION: {
    FONT_SIZE: "16px",
    FONT_WEIGHT: 500,
    LINE_HEIGHT: "1.25",
  },
} as const;

export const OPTION_SELECT_GROUP_COLORS = {
  SELECTED_BACKGROUND: SITE_COLORS.NAVY_DARK,
  SELECTED_TEXT: SITE_COLORS.WHITE,
  SELECTED_BORDER: SITE_COLORS.NAVY_DARK,
  UNSELECTED_BACKGROUND: SITE_COLORS.WHITE,
  UNSELECTED_TEXT: SITE_COLORS.TEXT_PRIMARY,
  UNSELECTED_BORDER: SITE_COLORS.GREY_5,
  QUESTION_TEXT: SITE_COLORS.TEXT_PRIMARY,
  ERROR_TEXT: SITE_COLORS.RED,
} as const;

export const OPTION_SELECT_GROUP_ERROR = {
  FONT_SIZE: "14px",
} as const;
