import { TRANSLATION_KEYS } from "@/utility/strings";

export const RATING_DEFAULTS = {
  MAX: 5,
  MIN: 0,
  SIZE: 16,
  GAP: 4,
  WRAPPER_GAP: "6px",
  STAR_PADDING: "2px",
  STAR_BORDER_RADIUS: "4px",
} as const;

export const RATING_TYPOGRAPHY = {
  LABEL: {
    FONT_SIZE: "12px",
    FONT_WEIGHT: "500",
    LINE_HEIGHT: "1.25",
    LETTER_SPACING: "0",
  },
} as const;

export const RATING_CONSTANTS = {
  LABEL_KEY: TRANSLATION_KEYS.RATING.LABEL,
  ARIA: {
    GROUP_KEY: TRANSLATION_KEYS.RATING.ARIA.GROUP,
    STAR_KEY: TRANSLATION_KEYS.RATING.ARIA.STAR,
    VALUE_KEY: TRANSLATION_KEYS.RATING.ARIA.VALUE,
  },
  SHOWCASE: {
    TITLE_KEY: TRANSLATION_KEYS.RATING.SHOWCASE.TITLE,
    INTERACTIVE_KEY: TRANSLATION_KEYS.RATING.SHOWCASE.INTERACTIVE,
    READ_ONLY_KEY: TRANSLATION_KEYS.RATING.SHOWCASE.READ_ONLY,
  },
} as const;
