import { SITE_COLORS } from "@/utility/strings";

export const SELECTABLE_SERVICE_CARD_DEFAULTS = {
  MAX_WIDTH: "304px",
  MIN_HEIGHT: "160px",
  PADDING: "20px 24px",
  BORDER_RADIUS: "16px",
  GAP: "16px",
  HEADER_GAP: "12px",
  CONTENT_GAP: "8px",
  ICON_SIZE: "48px",
  ICON_BORDER_RADIUS: "9999px",
  BADGE_PADDING: "4px 12px",
  BADGE_BORDER_RADIUS: "9999px",
  BORDER_WIDTH: "2px",
  SELECTED_BORDER_WIDTH: "2px",
  UNSELECTED_BORDER_WIDTH: "2px",
  CHECK_OFFSET_TOP: "20px",
  CHECK_OFFSET_RIGHT: "24px",
  CHECK_ICON_SIZE: "20px",
} as const;

export const SELECTABLE_SERVICE_CARD_TYPOGRAPHY = {
  TITLE: {
    FONT_SIZE: "18px",
    FONT_WEIGHT: 700,
    LINE_HEIGHT: "1.3",
  },
  DESCRIPTION: {
    FONT_SIZE: "14px",
    FONT_WEIGHT: 400,
    LINE_HEIGHT: "1.4",
  },
  BADGE: {
    FONT_SIZE: "12px",
    FONT_WEIGHT: 600,
  },
} as const;

export const SELECTABLE_SERVICE_CARD_COLORS = {
  BACKGROUND: SITE_COLORS.WHITE,
  TITLE: SITE_COLORS.TEXT_PRIMARY,
  DESCRIPTION: SITE_COLORS.GREY_4,
  SELECTED_BORDER: SITE_COLORS.NAVY_DARK,
  UNSELECTED_BORDER: SITE_COLORS.GREY_5,
  BADGE_BACKGROUND: "#E6F7F5",
  BADGE_TEXT: SITE_COLORS.TEAL_PRIMARY,
  ICON_INSTANT: "#E8F4FC",
  ICON_SCHEDULED: "#FFF4E8",
  ERROR_TEXT: SITE_COLORS.RED,
} as const;

export const SELECTABLE_SERVICE_CARD_ERROR = {
  FONT_SIZE: "14px",
} as const;
